displayName=Party Strikes
author=Zexohf
description=Give party members strikes when they mess up. Three strikes and you're out!
tags=party,strikes,fun,clan,group
version=
plugins=com.partystrikes.StrikesPlugin
build=standard
